# This is a basic workflow to help you get started with Actions

name: CI

# The workflow will run on creation of opening of Pull requesting or Issue
on:
  pull_request:
    types: opened
  issues:
    types: opened
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Trying to link PR to issue

      - name: auto link pull request
        # You may pin to the exact commit or the version.
        # uses: alisalemmi/auto-link-issue@baa7ec705f98ea5ce635c4730c47eb6d526001f4
        uses: alisalemmi/auto-link-issue@v1.0.0
        with:
          # github token
          github_token: ${{ secrets. GITHUB_TOKEN }}
